// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReleaseNotes.Repository.Context;

#nullable disable

namespace ReleaseNotes.Repository.Migrations
{
    [DbContext(typeof(NpgSqlContext))]
    [Migration("20220112133218_rename DB")]
    partial class renameDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Calls.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CallId")
                        .HasColumnType("bigint");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CallId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Calls.Call", b =>
                {
                    b.Property<long>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CallId"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FeedbackId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean");

                    b.Property<int>("PriorityDegree")
                        .HasColumnType("integer");

                    b.Property<int>("Software")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CallId");

                    b.HasIndex("FeedbackId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Email.Receiver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SenderEmailConfigId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SenderEmailConfigId");

                    b.ToTable("Receivers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "d.rodrigues0505@gmail.com",
                            Name = "David Rodrigues",
                            SenderEmailConfigId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Email = "analise@supercontrole.com",
                            Name = "Rogério Trevisan",
                            SenderEmailConfigId = 1L
                        });
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Email.Sender", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SenderEmailConfigId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SenderEmailConfigId")
                        .IsUnique();

                    b.ToTable("Senders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "desenvolvimento04@supercontrole.com",
                            Name = "SuperControle Chamados",
                            SenderEmailConfigId = 1L
                        });
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Email.SenderEmailConfig", b =>
                {
                    b.Property<long>("SenderConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SenderConfigId"));

                    b.HasKey("SenderConfigId");

                    b.ToTable("SenderEmailConfig");

                    b.HasData(
                        new
                        {
                            SenderConfigId = 1L
                        });
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Feedback.ReleasesFeedback", b =>
                {
                    b.Property<long>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FeedbackId"));

                    b.Property<long?>("CallId")
                        .HasColumnType("bigint");

                    b.Property<string>("Details")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackDate")
                        .HasColumnType("text");

                    b.Property<int>("FeedbackFrom")
                        .HasColumnType("integer");

                    b.Property<bool>("FeedbackPositive")
                        .HasColumnType("boolean");

                    b.Property<long?>("ModulePdvId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModulePowerServerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("OpenCall")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CallId");

                    b.HasIndex("ModulePdvId");

                    b.HasIndex("ModulePowerServerId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerPDV.ModulePDV", b =>
                {
                    b.Property<long>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ModuleId"));

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReleaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ModuleId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ModulePDVs");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerPDV.ReleasePDV", b =>
                {
                    b.Property<long>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReleaseId"));

                    b.Property<string>("VersionDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReleaseId");

                    b.ToTable("ReleasePDVs");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerServer.ModulePowerServer", b =>
                {
                    b.Property<long>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ModuleId"));

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReleaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ModuleId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerServer.ReleasePowerServer", b =>
                {
                    b.Property<long>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReleaseId"));

                    b.Property<string>("VersionDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReleaseId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Calls.Attachment", b =>
                {
                    b.HasOne("ReleaseNotes.Entities.Model.Calls.Call", "Call")
                        .WithMany("Attachments")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Calls.Call", b =>
                {
                    b.HasOne("ReleaseNotes.Entities.Model.Feedback.ReleasesFeedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackId");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Email.Receiver", b =>
                {
                    b.HasOne("ReleaseNotes.Entities.Model.Email.SenderEmailConfig", "SenderEmailConfig")
                        .WithMany("Receivers")
                        .HasForeignKey("SenderEmailConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenderEmailConfig");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Email.Sender", b =>
                {
                    b.HasOne("ReleaseNotes.Entities.Model.Email.SenderEmailConfig", "SenderEmailConfig")
                        .WithOne("Sender")
                        .HasForeignKey("ReleaseNotes.Entities.Model.Email.Sender", "SenderEmailConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenderEmailConfig");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Feedback.ReleasesFeedback", b =>
                {
                    b.HasOne("ReleaseNotes.Entities.Model.Calls.Call", "Call")
                        .WithMany()
                        .HasForeignKey("CallId");

                    b.HasOne("ReleaseNotes.Entities.Model.ReleasesPowerPDV.ModulePDV", "ModulePDV")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ModulePdvId");

                    b.HasOne("ReleaseNotes.Entities.Model.ReleasesPowerServer.ModulePowerServer", "ModulePowerServer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ModulePowerServerId");

                    b.Navigation("Call");

                    b.Navigation("ModulePDV");

                    b.Navigation("ModulePowerServer");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerPDV.ModulePDV", b =>
                {
                    b.HasOne("ReleaseNotes.Entities.Model.ReleasesPowerPDV.ReleasePDV", "Release")
                        .WithMany("Modules")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerServer.ModulePowerServer", b =>
                {
                    b.HasOne("ReleaseNotes.Entities.Model.ReleasesPowerServer.ReleasePowerServer", "Release")
                        .WithMany("Modules")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Calls.Call", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.Email.SenderEmailConfig", b =>
                {
                    b.Navigation("Receivers");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerPDV.ModulePDV", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerPDV.ReleasePDV", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerServer.ModulePowerServer", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("ReleaseNotes.Entities.Model.ReleasesPowerServer.ReleasePowerServer", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
